### PR TITLE
Try to enables Mac OS X again

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Tests failed when using multi cores:
```

Running tests
=============
1 of 17 (atomics)... OK 
2 of 17 (gemm)... OK 
3 of 17 (gemmflags)... OK 
4 of 17 (hash)... OK 
5 of 17 (headeronly)... OK 
6 of 17 (malloc)... OK 
7 of 17 (matcopy)... OK 
8 of 17 (matdiff)... OK 
9 of 17 (math)... OK 
10 of 17 (memory)... OK 
11 of 17 (mhd)... OK 
12 of 17 (registry)... OK 
13 of 17 (rng)... OK 
14 of 17 (threadsafety)... OK 
15 of 17 (timer)... FAILED(13) 
make: *** [Makefile:1272: tests] Error 2
```

**Comment by ltalirz** [comment]
Just to understand: what do you mean by "when using multicores"?

If I understand correctly, then this is again a random failure, happening after the [exact same test passed fine on the same build](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=263603&view=logs&j=58ac6aab-c4bc-5de2-2894-98e408cc8ec9&t=933f325c-924e-533d-4d95-e93b5843ce8b&l=1343).
Should we perhaps open an issue on https://github.com/hfp/libxsmm/issues ?

**Comment by jan-janssen** [comment]
The Mac OS X tests worked here https://github.com/conda-forge/libxsmm-feedstock/pull/13/commits/abdba94aba3f09999f6341a27ded6b216d0c7efe In abdba94

**Comment by ltalirz** [comment]
Opened https://github.com/hfp/libxsmm/issues/454

**Pull request merged**
